version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: on-failure

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/static_backend/
      - media:/app/media_backend/
    depends_on:
      - db
    restart: on-failure

  nginx:
    image: nginx:1.24.0
    env_file: .env
    ports:
      - ${DOCKER_PORTS}
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/usr/share/nginx/html/media_backend/
      - static:/usr/share/nginx/html/static_backend/
    restart: on-failure